name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
         
          script: |
            mkdir github actions #create a destination folder
            cd github actions #enter the folder created
            git clone git@github.com:Mulubwa17/ci-cd-to-digitalocean-with-github-actions.git #clone the repositroy into the folder you have entered
            echo 'repository has been cloned successfully' #message output to show whne the operation has been successfull

